export const CATEGORIES = {
  castle:    { label: "Castle / Fortress",    emoji: "🏰", color: "#7F77DD" },
  church:    { label: "Church / Monastery",   emoji: "⛪", color: "#D85A30" },
  museum:    { label: "Museum",               emoji: "🏛",  color: "#185FA5" },
  nature:    { label: "Nature / Outdoors",    emoji: "🌿", color: "#1D9E75" },
  city:      { label: "Old Town / City",      emoji: "🏙",  color: "#BA7517" },
  viewpoint: { label: "Viewpoint / Scenic",   emoji: "🌄", color: "#639922" },
};

// Fallback image per category (verified Unsplash IDs). A spot's own `image`
// overrides this; if a curated image fails to load the UI falls back to these.
export const CATEGORY_IMAGES = {
  castle:    "https://images.unsplash.com/photo-1601244005535-a48d21d951ac?w=600&q=80",
  church:    "https://images.unsplash.com/photo-1571406252241-db0280bd36cd?w=600&q=80",
  museum:    "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
  nature:    "https://images.unsplash.com/photo-1566274360960-0b67d9498c04?w=600&q=80",
  city:      "https://images.unsplash.com/photo-1564760055775-d63b17a55c44?w=600&q=80",
  viewpoint: "https://images.unsplash.com/photo-1549887534-1541e9326642?w=600&q=80",
};

// Main route stops — coords corrected from location database
export const STOPS = [
  {
    id: "otp",
    name: "Bucharest Airport (OTP)", shortName: "Bucharest",
    coords: [44.572, 26.102],
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
  },
  {
    id: "snagov",
    name: "Snagov", shortName: "Snagov",
    coords: [44.7095, 26.1530],   // Hotel Snagov Club coords
    image: "https://images.unsplash.com/photo-1566274360960-0b67d9498c04?w=600&q=80",
    region: "Ilfov County, Muntenia",
    about: "Snagov is a scenic commune built around Lake Snagov, the largest natural lake in Romania (600 ha, 16 km long). Famous as the legendary burial site of Vlad the Impaler (Dracula).",
    wikipedia: "https://en.wikipedia.org/wiki/Snagov",
  },
  {
    id: "sinaia",
    name: "Sinaia", shortName: "Sinaia",
    coords: [45.3535, 25.5520],   // Hotel Sinaia coords
    image: "https://images.unsplash.com/photo-1549887534-1541e9326642?w=600&q=80",
    region: "Prahova County, Muntenia",
    about: "Known as the 'Pearl of the Carpathians,' Sinaia is a royal mountain resort town nestled in the Bucegi Mountains. King Carol I built his summer residence Peleș Castle here.",
    wikipedia: "https://en.wikipedia.org/wiki/Sinaia",
  },
  {
    id: "brasov",
    name: "Brașov", shortName: "Brașov",
    coords: [45.6450, 25.5940],   // The Pines Boutique Villa coords
    image: "https://images.unsplash.com/photo-1564760055775-d63b17a55c44?w=600&q=80",
    region: "Brașov County, Transylvania",
    about: "One of Romania's most visited cities — a medieval jewel in the heart of Transylvania, surrounded by forested mountains. Known for its Gothic Black Church and proximity to Bran Castle.",
    wikipedia: "https://en.wikipedia.org/wiki/Bra%C8%99ov",
  },
  {
    id: "sibiu",
    name: "Sibiu / Gura Râului", shortName: "Sibiu",
    coords: [45.6700, 23.9150],   // Pensiunea La Vâltoare coords (Gura Râului, 18 km from Sibiu)
    image: "https://images.unsplash.com/photo-1571406252241-db0280bd36cd?w=600&q=80",
    region: "Sibiu County, Transylvania",
    about: "One of Romania's most beautifully preserved medieval cities (Hermannstadt). European Capital of Culture 2007. Staying in Gura Râului village, 18 km from Sibiu city center.",
    wikipedia: "https://en.wikipedia.org/wiki/Sibiu",
  },
  {
    id: "curtea",
    name: "Curtea de Argeș", shortName: "Curtea de Argeș",
    coords: [45.1392, 24.6792],   // Old Court coords
    image: "https://images.unsplash.com/photo-1601244005535-a48d21d951ac?w=600&q=80",
    region: "Argeș County, Muntenia",
    about: "One of the oldest towns in Wallachia and former medieval capital. The Royal Necropolis holds the tombs of Romanian kings. Gateway to the Transfăgărășan and Poienari Fortress.",
    wikipedia: "https://en.wikipedia.org/wiki/Curtea_de_Arge%C8%99",
  },
];

// All attractions from location database, with real coordinates.
// note = short teaser (used on the map + collapsed row)
// desc = fuller description shown when a spot is expanded
// duration = suggested visit time
export const SPOTS = [
  // ── SNAGOV ──────────────────
  { id: 1,  name: "Snagov Monastery",              stop: "snagov", cat: "church",    coords: [44.7300, 26.1330], duration: "1–2 h",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/M%C3%A2n%C4%83stirea_Snagov.jpg/960px-M%C3%A2n%C4%83stirea_Snagov.jpg",
    note: "14th-c. island monastery — legendary tomb of Vlad the Impaler. Reachable by boat.",
    desc: "A serene 14th-century monastery on a small island in Lake Snagov, reached by boat. Legend says the headless body of Vlad the Impaler (Dracula) was buried here beneath a stone slab near the altar. Faded frescoes and the peaceful island setting make it the area's must-see." },
  { id: 2,  name: "Snagov Palace",                 stop: "snagov", cat: "castle",    coords: [44.7150, 26.1300], duration: "30–45 min",
    image: "https://upload.wikimedia.org/wikipedia/commons/e/e0/Palat_snagov.jpg",
    note: "Former royal palace built by Prince Nicholas of Romania in 1928.",
    desc: "An elegant royal residence built in 1928 for Prince Nicholas of Romania, tucked among the forests on the lakeshore. Its neo-Romanian architecture and manicured grounds hint at the area's aristocratic past." },
  { id: 3,  name: "Snagov Lake",                   stop: "snagov", cat: "nature",    coords: [44.7250, 26.1480], duration: "1–3 h",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Snagov_water_lilies.jpg/960px-Snagov_water_lilies.jpg",
    note: "Largest natural lake in Romania (600 ha, 16 km long). Motorboat tours available.",
    desc: "Romania's largest natural lake — a 16-km ribbon of water covering 600 hectares, framed by oak forest. A favourite weekend escape from Bucharest for boating, kayaking and lakeside dining." },
  { id: 4,  name: "Snagov Natural Complex Reserve",stop: "snagov", cat: "nature",    coords: [44.7100, 26.1600], duration: "1–2 h",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Flickr_-_fusion-of-horizons_-_Snagov_%2834%29.jpg/960px-Flickr_-_fusion-of-horizons_-_Snagov_%2834%29.jpg",
    note: "1,147 ha nature reserve — lake and old oak forests.",
    desc: "A 1,147-hectare protected reserve of open water and ancient oak groves, home to rich birdlife and rare water plants. Quiet trails and shoreline make it ideal for a slow nature walk." },
  { id: 5,  name: "Snagov Eco-Tourism Center",     stop: "snagov", cat: "nature",    coords: [44.7200, 26.1450], duration: "1–2 h",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Snagov_water_lilies.jpg/960px-Snagov_water_lilies.jpg",
    note: "Bike rentals, kayaks, audio-guided boat tours, 5 cycling circuits.",
    desc: "The hub for active exploration of the lake: rent bikes or kayaks, join an audio-guided boat tour, or follow one of five signposted cycling circuits through the forest." },
  { id: 6,  name: "Snagov Museum",                 stop: "snagov", cat: "museum",    coords: [44.7080, 26.1520], duration: "45 min",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Flickr_-_fusion-of-horizons_-_Snagov_%2834%29.jpg/960px-Flickr_-_fusion-of-horizons_-_Snagov_%2834%29.jpg",
    note: "Collections on 130 personalities connected to Snagov. Opened 2008.",
    desc: "A small local museum opened in 2008, telling the stories of some 130 personalities connected to Snagov across the centuries — from royalty to writers and artists." },

  // ── SINAIA ──────────────────
  { id: 7,  name: "Peleș Castle",                  stop: "sinaia", cat: "castle",    coords: [45.3600, 25.5370], duration: "1.5–2 h",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/01_Chateau_Peles.jpg/960px-01_Chateau_Peles.jpg",
    note: "Neo-Renaissance royal palace — Tripadvisor #1 attraction in Sinaia.",
    desc: "The crown jewel of Sinaia and one of Europe's most beautiful castles — a Neo-Renaissance masterpiece completed in 1883 as King Carol I's summer residence. Its 160+ rooms brim with carved wood, stained glass, armour and art. Tripadvisor's #1 attraction in town." },
  { id: 8,  name: "Pelișor Castle",                stop: "sinaia", cat: "castle",    coords: [45.3610, 25.5360], duration: "1 h",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Pelisor_Castle%2C_Sinaia.jpg/960px-Pelisor_Castle%2C_Sinaia.jpg",
    note: "Art Nouveau royal retreat, built for King Ferdinand I and Queen Marie.",
    desc: "A smaller, more intimate Art Nouveau retreat beside Peleș, built for King Ferdinand I and Queen Marie. Queen Marie's shimmering Golden Room and Byzantine-inspired interiors are the highlight." },
  { id: 9,  name: "Sinaia Monastery",              stop: "sinaia", cat: "church",    coords: [45.3510, 25.5490], duration: "45 min–1 h",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Sinaia_Monastery_%2853743443033%29.jpg/960px-Sinaia_Monastery_%2853743443033%29.jpg",
    note: "Founded 1695 — the namesake of the town. Beautiful Orthodox complex.",
    desc: "Founded in 1695 and named after Mount Sinai, this walled Orthodox monastery gave the town its name. Two churches, a tranquil courtyard and a small museum of religious art." },
  { id: 10, name: "Sinaia Casino",                 stop: "sinaia", cat: "city",      coords: [45.3500, 25.5520], duration: "30 min",
    image: "https://upload.wikimedia.org/wikipedia/en/thumb/d/d0/Casino_Sinaia%2C_2017.jpg/960px-Casino_Sinaia%2C_2017.jpg",
    note: "Historic 1913 Belle Époque building, now a conference center.",
    desc: "A grand Belle Époque casino from 1913, modelled on Monte Carlo. The gaming tables are long gone — today it hosts events and conferences — but the ornate halls and gardens are worth a look." },
  { id: 11, name: "Bucegi Cable Car",              stop: "sinaia", cat: "viewpoint", coords: [45.3490, 25.5470], duration: "2–4 h",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Muntii_Bucegi_vazuti_de_pe_Postavaru.jpg/960px-Muntii_Bucegi_vazuti_de_pe_Postavaru.jpg",
    note: "Connects resort with Cota 1,400 and Cota 2,000 mountain platforms.",
    desc: "The Sinaia gondola climbs from the resort to Cota 1400 and on to Cota 2000, opening up sweeping views and access to high-altitude hiking trails on the Bucegi plateau." },
  { id: 12, name: "Bucegi Natural Park",           stop: "sinaia", cat: "nature",    coords: [45.3960, 25.4670], duration: "half day+",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Bucegi_mountains%2C_%27on_fire%27.jpg/960px-Bucegi_mountains%2C_%27on_fire%27.jpg",
    note: "326 km² of protected mountain terrain, hiking trails, alpine flora.",
    desc: "326 km² of protected mountain wilderness with dramatic ridges, alpine meadows and famous rock formations like the Sphinx and Babele. A paradise for hikers." },
  { id: 13, name: "George Enescu Memorial House",  stop: "sinaia", cat: "museum",    coords: [45.3520, 25.5480], duration: "45 min",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/RO_PH_Sinaia_George_Enescu_memorial_house.jpg/960px-RO_PH_Sinaia_George_Enescu_memorial_house.jpg",
    note: "Villa of Romania's greatest composer.",
    desc: "The villa 'Luminiș', home of Romania's greatest composer George Enescu, preserved with his personal belongings and set in a tranquil forest garden." },

  // ── BRAȘOV ──────────────────
  { id: 14, name: "Black Church",                  stop: "brasov", cat: "church",    coords: [45.6410, 25.5880], duration: "45 min–1 h",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/20140628_Bra%C5%9Fov_12.jpg/960px-20140628_Bra%C5%9Fov_12.jpg",
    note: "14th–15th c. Gothic church — the largest Gothic church in Romania.",
    desc: "Romania's largest Gothic church, built between 1383 and 1477. Its nickname comes from soot left by a great fire in 1689. Inside are a monumental organ and a renowned collection of Anatolian carpets." },
  { id: 15, name: "Council Square (Piața Sfatului)",stop: "brasov", cat: "city",     coords: [45.6420, 25.5890], duration: "1 h",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Brasov%2C_Piata_Sfatului.jpg/960px-Brasov%2C_Piata_Sfatului.jpg",
    note: "The stunning medieval heart of the old town.",
    desc: "The postcard-perfect heart of Brașov's old town, ringed by colourful Baroque merchant houses and dominated by the 15th-century Council House. Cafés, street life and the start of every old-town walk." },
  { id: 16, name: "Catherine's Gate",              stop: "brasov", cat: "castle",    coords: [45.6480, 25.5850], duration: "20 min",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/EcaterinaBv.jpg/960px-EcaterinaBv.jpg",
    note: "The only surviving original medieval city gate.",
    desc: "The only surviving medieval city gate of Brașov (1559), with fairy-tale turrets. Its four corner towers symbolised the town's right to pass death sentences." },
  { id: 17, name: "Tampa Mountain",                stop: "brasov", cat: "viewpoint", coords: [45.6370, 25.6050], duration: "1.5–2 h",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/RO_BV_Bra%C5%9Fov%2C_T%C3%A2mpa_2.jpg/960px-RO_BV_Bra%C5%9Fov%2C_T%C3%A2mpa_2.jpg",
    note: "900 m peak — cable car or hike up for panoramic views of the city.",
    desc: "The forested peak that rises straight above the old town, crowned with a Hollywood-style BRAȘOV sign. Ride the cable car or hike up for the finest panorama of the medieval centre." },
  { id: 18, name: "Bran Castle",                   stop: "brasov", cat: "castle",    coords: [45.5130, 25.3700], duration: "1.5–2 h",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Castelul_Bran2.jpg/960px-Castelul_Bran2.jpg",
    note: "'Dracula's Castle' — Gothic fortress, 30 min from Brașov.",
    desc: "The famous 'Dracula's Castle' — a dramatic 14th-century fortress perched on a rock and marketed on the Bram Stoker legend. Narrow stairs, period rooms and Queen Marie's history make it a bucket-list stop, about 30 min from Brașov." },
  { id: 19, name: "Poiana Brașov",                 stop: "brasov", cat: "nature",    coords: [45.5930, 25.5490], duration: "half day",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Poiana_Brasov.jpg/960px-Poiana_Brasov.jpg",
    note: "Top ski resort and nature area, 12 km from the city.",
    desc: "Romania's premier mountain resort, 12 km from the city — meadows and ski slopes in a bowl beneath Postăvarul peak, with a cable car, restaurants and easy alpine walks." },
  { id: 20, name: "Râșnov Fortress",               stop: "brasov", cat: "castle",    coords: [45.5890, 25.4590], duration: "1–1.5 h",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Cetatea_R%C3%A2%C8%99nov%2C_v%C4%83zut%C4%83_din_%C8%99oseaua_Cristian-R%C3%A2%C8%99nov..jpg/960px-Cetatea_R%C3%A2%C8%99nov%2C_v%C4%83zut%C4%83_din_%C8%99oseaua_Cristian-R%C3%A2%C8%99nov..jpg",
    note: "Restored medieval peasant fortress above the town of Râșnov.",
    desc: "A superbly preserved 13th-century peasant citadel on a hilltop above Râșnov, built by villagers as a refuge. Great ramparts and valley views, easily combined with a Bran visit." },
  { id: 21, name: "Libearty Bear Sanctuary",       stop: "brasov", cat: "nature",    coords: [45.5670, 25.3080], duration: "2 h",
    note: "One of the largest bear sanctuaries in Europe (Zărnești).",
    desc: "One of Europe's largest brown-bear sanctuaries, near Zărnești, home to bears rescued from captivity roaming 69 hectares of oak forest. Visits are by guided morning tour only." },
  { id: 22, name: "First Romanian School Museum",  stop: "brasov", cat: "museum",    coords: [45.6390, 25.5840], duration: "45 min",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/RO_BV_Prima_%C5%9Fcoal%C4%83.jpg/960px-RO_BV_Prima_%C5%9Fcoal%C4%83.jpg",
    note: "Home to Romania's first printing press.",
    desc: "In the Șchei district, the site of Romania's first school and printing press, displaying old manuscripts, early Romanian books and the legacy of Deacon Coresi." },
  { id: 23, name: "Rope Street",                   stop: "brasov", cat: "city",      coords: [45.6430, 25.5910], duration: "10 min",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Brasov_-_Strada_Sforii_%282023%29_-_img_02.jpg/960px-Brasov_-_Strada_Sforii_%282023%29_-_img_02.jpg",
    note: "The narrowest street in Romania.",
    desc: "Strada Sforii — one of the narrowest streets in Europe (just 1.1–1.35 m wide), a quirky passage squeezed between two rows of old houses. A fun two-minute photo stop." },
  { id: 24, name: "St. Nicholas Church (Șchei)",   stop: "brasov", cat: "church",    coords: [45.6370, 25.5830], duration: "30 min",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Biserica_Sf%C3%A2ntul_Nicolae_din_Bra%C8%99ov_%282023%29_-_img_08.jpg/960px-Biserica_Sf%C3%A2ntul_Nicolae_din_Bra%C8%99ov_%282023%29_-_img_08.jpg",
    note: "14th c. Orthodox church in the historic Romanian neighborhood.",
    desc: "A striking 14th-century Orthodox church in the historic Romanian Șchei quarter, with a soaring spire and a churchyard tied to the birth of Romanian-language education." },

  // ── SIBIU ───────────────────
  { id: 25, name: "Piața Mare (Great Square)",     stop: "sibiu",  cat: "city",      coords: [45.7970, 24.1500], duration: "1 h",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Centrul_Istoric_Sibiu.jpg/960px-Centrul_Istoric_Sibiu.jpg",
    note: "The grand main square surrounded by Baroque and Renaissance buildings.",
    desc: "Sibiu's magnificent Great Square, one of the largest in Transylvania, lined with pastel Baroque palaces and watched over by the city's famous eyelid-shaped roof windows — the 'eyes of Sibiu'." },
  { id: 26, name: "Bridge of Lies",                stop: "sibiu",  cat: "city",      coords: [45.7960, 24.1510], duration: "15 min",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/RO_SB_Bridge_of_Lies_02.jpg/960px-RO_SB_Bridge_of_Lies_02.jpg",
    note: "Romania's first cast-iron bridge (1859) with a famous local legend.",
    desc: "Romania's first cast-iron bridge (1859), wrapped in legends that it will creak or collapse if a lie is told upon it. A short, atmospheric crossing in the upper town." },
  { id: 27, name: "Saint Mary Evangelical Church", stop: "sibiu",  cat: "church",    coords: [45.7970, 24.1490], duration: "45 min",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/RO_SB_Saint_Mary_Lutheran_church_1.jpg/960px-RO_SB_Saint_Mary_Lutheran_church_1.jpg",
    note: "Gothic Lutheran church — the most important in Transylvania.",
    desc: "A monumental Gothic Lutheran church whose 73-m tower is Sibiu's landmark. Climb it for rooftop views; inside are a huge fresco and the tomb of Mihnea the Bad." },
  { id: 28, name: "Brukenthal National Museum",    stop: "sibiu",  cat: "museum",    coords: [45.7970, 24.1500], duration: "1.5–2 h",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Brukenthal-sibiu.jpg/960px-Brukenthal-sibiu.jpg",
    note: "Art, History, Pharmacy & Natural History museums in a Baroque palace.",
    desc: "The oldest museum in Romania (opened 1817), set in Baron Brukenthal's Baroque palace on the Great Square. European old-master paintings plus history, pharmacy and natural-history collections." },
  { id: 29, name: "ASTRA Open Air Museum",         stop: "sibiu",  cat: "museum",    coords: [45.7730, 24.1210], duration: "half day",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/ASTRA_National_Museum_Complex_%2C_main_entrance_of_the_Open_air_museum%2C_Sibiu.jpg/960px-ASTRA_National_Museum_Complex_%2C_main_entrance_of_the_Open_air_museum%2C_Sibiu.jpg",
    note: "96-hectare open-air ethnography museum in Dumbrava Forest.",
    desc: "A vast 96-hectare open-air ethnographic museum in Dumbrava forest, with hundreds of relocated traditional houses, mills and workshops along lakeside paths. Allow plenty of time to wander." },
  { id: 30, name: "Dumbrava Sibiului Natural Park",stop: "sibiu",  cat: "nature",    coords: [45.7750, 24.1180], duration: "1–2 h",
    image: "https://upload.wikimedia.org/wikipedia/commons/c/c8/Muzeul_satului_sibiu_lac.JPG",
    note: "960 ha forest park, 4 km from city center.",
    desc: "A 960-hectare forest park just outside the city with shaded trails, a lake and the ASTRA museum — perfect for a relaxed walk or bike ride." },
  { id: 31, name: "Council Tower & Stairs Tower",  stop: "sibiu",  cat: "viewpoint", coords: [45.7970, 24.1510], duration: "30 min",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/RO_SB_Council_tower.jpg/960px-RO_SB_Council_tower.jpg",
    note: "Medieval watchtowers with panoramic views over the old town.",
    desc: "The medieval Council Tower links the Great and Small Squares; climb its steep stairs for one of the best panoramas over Sibiu's terracotta rooftops and the distant Făgăraș mountains." },
  { id: 32, name: "Transfăgărășan Highway",        stop: "sibiu",  cat: "viewpoint", coords: [45.6020, 24.6180], duration: "half–full day",
    image: "https://upload.wikimedia.org/wikipedia/commons/7/74/Romania-roads-DN7C.png",
    note: "'Best road in the world' (Top Gear). ~45 min from Sibiu.",
    desc: "Crowned 'the best road in the world' by Top Gear — a breathtaking mountain highway of hairpin bends climbing over 2,000 m through the Făgăraș range. Open roughly July–October; about 45 min from Sibiu to the start." },
  { id: 33, name: "Păltiniș Ski Resort",           stop: "sibiu",  cat: "nature",    coords: [45.6400, 23.9300], duration: "half day",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/P%C4%83ltini%C5%9F_iarna19.JPG/960px-P%C4%83ltini%C5%9F_iarna19.JPG",
    note: "19 km from the guesthouse at Gura Râului.",
    desc: "Romania's oldest mountain resort at 1,440 m, 19 km from Gura Râului — pine forests and easy trails in summer, ski slopes in winter, and crisp alpine air year-round." },
  { id: 34, name: "Sighișoara (day trip)",         stop: "sibiu",  cat: "city",      coords: [46.2200, 24.7930], duration: "half day",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Casa_cu_cerbi.JPG/960px-Casa_cu_cerbi.JPG",
    note: "Dracula's birthplace — UNESCO World Heritage medieval fortress town. 1 hr from Sibiu.",
    desc: "A jewel-box UNESCO World Heritage citadel and the birthplace of Vlad the Impaler. Cobbled lanes, the iconic Clock Tower and colourful guild houses crown the hill; about an hour from Sibiu." },

  // ── CURTEA DE ARGEȘ ────────────
  { id: 35, name: "Curtea de Argeș Cathedral",     stop: "curtea", cat: "church",    coords: [45.1430, 24.6740], duration: "1 h",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Man_Curtea_de_Arges.SV.jpg/960px-Man_Curtea_de_Arges.SV.jpg",
    note: "Romania's most important Orthodox site & Royal Necropolis (tombs of Romanian kings).",
    desc: "A dazzling, ornately curved Orthodox monastery church (1512–1517) and Romania's Royal Necropolis, holding the tombs of the modern kings and queens. Legend says its builder walled in his own wife to complete it." },
  { id: 36, name: "Princely Court (Curtea Domnească)", stop: "curtea", cat: "castle", coords: [45.1400, 24.6780], duration: "45 min",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Curtea_de_Arges.SV.jpg/960px-Curtea_de_Arges.SV.jpg",
    note: "Ruins of the medieval Wallachian royal palace with 14th-c. St. Nicholas Church.",
    desc: "The ruins of the 14th-century royal palace of Wallachia, with the beautifully frescoed St. Nicholas Church at its centre — one of the country's oldest surviving monuments." },
  { id: 37, name: "Vidraru Dam & Lake",            stop: "curtea", cat: "viewpoint", coords: [45.3520, 24.6220], duration: "1–2 h",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Vidraru_Dam.jpg/960px-Vidraru_Dam.jpg",
    note: "One of the largest dams in Romania — dramatic lake and mountain scenery. 30 km away.",
    desc: "A colossal 166-m arch dam (1966) holding back a fjord-like reservoir amid the mountains, with a giant Prometheus statue nearby. Dramatic scenery about 30 km up the valley." },
  { id: 38, name: "Transfăgărășan Highway (south)",stop: "curtea", cat: "viewpoint", coords: [45.3000, 24.6000], duration: "half–full day",
    image: "https://upload.wikimedia.org/wikipedia/commons/7/74/Romania-roads-DN7C.png",
    note: "Tripadvisor #1 in the area. Iconic mountain road starts near Curtea de Argeș.",
    desc: "The southern approach to the legendary Transfăgărășan begins near Curtea de Argeș, winding past Vidraru toward the high passes — Tripadvisor's #1 experience in the area." },
  { id: 39, name: "Poienari Fortress",             stop: "curtea", cat: "castle",    coords: [45.3550, 24.6380], duration: "1.5–2 h",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/PoienariCastle1.jpg/960px-PoienariCastle1.jpg",
    note: "The REAL castle of Vlad the Impaler — ruins atop a cliff via 1,480 steps.",
    desc: "The REAL castle of Vlad the Impaler — ruined ramparts clinging to a cliff, reached by climbing 1,480 forest steps. Far less touristy than Bran and steeped in genuine Dracula history." },
  { id: 40, name: "Bâlea Lake & Waterfall",        stop: "curtea", cat: "nature",    coords: [45.6010, 24.6170], duration: "2–3 h",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Bileato.jpg/960px-Bileato.jpg",
    note: "High-altitude glacial lake accessible via the Transfăgărășan.",
    desc: "A stunning glacial lake at 2,034 m on the crest of the Transfăgărășan, mirrored by surrounding peaks and reachable by road in summer or by cable car from Bâlea Cascadă. Alpine and unforgettable." },
  { id: 41, name: "Museum of Art & Argeș County",  stop: "curtea", cat: "museum",    coords: [45.1380, 24.6750], duration: "45 min",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Muzeul_Jude%C5%A3ean_Arge%C5%9F.jpg/960px-Muzeul_Jude%C5%A3ean_Arge%C5%9F.jpg",
    note: "Local history, art and cultural heritage of the Argeș region.",
    desc: "A compact museum tracing the art, history and folk heritage of the Argeș region — a good rainy-day stop in the town centre." },

  // ── Added from saved Google Maps list "טיול רומניה" ──────────────
  { id: 42, name: "Black Tower (Turnul Negru)",     stop: "brasov", cat: "viewpoint", coords: [45.6414, 25.5857], duration: "30–45 min",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Elemente_de_fortificare_exterioar%C4%83%2CTurnul_Negru%2C_Turnul_Alb%2C_Bra%C8%99ov_02.JPG/960px-Elemente_de_fortificare_exterioar%C4%83%2CTurnul_Negru%2C_Turnul_Alb%2C_Bra%C8%99ov_02.JPG",
    note: "Medieval watchtower on a rock above the old town — great Brașov panorama.",
    desc: "A restored 15th-century defensive tower perched on Warthe hill just above Brașov's old town. A short climb rewards you with one of the best free viewpoints over the medieval centre and the Black Church." },
  { id: 43, name: "Alpin Coaster Fundata",          stop: "brasov", cat: "nature",    coords: [45.4504, 25.2940], duration: "1–2 h",
    note: "Mountain slide / alpine roller-coaster near Bran, in the Fundata pass.",
    desc: "A gravity-powered alpine coaster winding down the meadows of the Fundata pass between Bran and Moieciu — a fun, scenic ride for all ages with sweeping views of the Piatra Craiului range." },
  { id: 44, name: "Cascada Mică Moieciu de Sus",    stop: "brasov", cat: "nature",    coords: [45.4286, 25.3316], duration: "30–45 min",
    note: "Small waterfall and short walk above the village of Moieciu de Sus.",
    desc: "A pretty little waterfall reached by a short walk from Moieciu de Sus, deep in the Bran–Moieciu valley. An easy, quiet nature stop to combine with a drive over the Fundata pass." },
  { id: 45, name: "Zărnești Cliffs (Prăpăstiile Zărneștiului)", stop: "brasov", cat: "nature", coords: [45.5253, 25.2698], duration: "2–3 h",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Pr%C4%83p%C4%83stiile_Z%C4%83rne%C8%99tiului.jpg/960px-Pr%C4%83p%C4%83stiile_Z%C4%83rne%C8%99tiului.jpg",
    note: "Dramatic narrow limestone gorge at the foot of Piatra Craiului.",
    desc: "A spectacular narrow limestone gorge near Zărnești where the cliffs close in to just a few metres. An easy, mostly flat trail threads through it — the classic gateway walk into Piatra Craiului National Park." },
  { id: 46, name: "Adventure Park Brașov",          stop: "brasov", cat: "nature",    coords: [45.6133, 25.6378], duration: "2–3 h",
    note: "Forest adventure park with zip-lines and rope courses on Tâmpa's slopes.",
    desc: "A tree-top adventure park on the wooded slopes near Brașov, with graded rope courses, zip-lines and obstacles for kids and adults. A good active half-day among the pines." },
  { id: 47, name: "Aquatic Paradise Brașov",        stop: "brasov", cat: "nature",    coords: [45.6731, 25.5859], duration: "half day",
    note: "Large indoor/outdoor water park on the edge of Brașov.",
    desc: "Brașov's big water park, with indoor and outdoor pools, slides and wave features. A relaxed family stop or a rainy-day alternative to sightseeing." },
  { id: 48, name: "Seven Ladders Canyon (Canionul Șapte Scări)", stop: "brasov", cat: "nature", coords: [45.5669, 25.6440], duration: "3–4 h",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Canionul_Sapte_Scari.jpg/960px-Canionul_Sapte_Scari.jpg",
    note: "Gorge climbed via seven metal-ladder waterfalls in the Piatra Mare massif.",
    desc: "A thrilling canyon in the Piatra Mare mountains near Timișu de Jos, ascended by a series of seven steel ladders and walkways bolted beside cascading waterfalls. There's also a zip-line descent option. Sturdy shoes required." },
  { id: 49, name: "Bolboci Lake",                   stop: "sinaia", cat: "nature",    coords: [45.3467, 25.4278], duration: "1–2 h",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/BolbociLake.JPG/960px-BolbociLake.JPG",
    note: "Alpine reservoir on the Bucegi plateau, reached by mountain road from Sinaia.",
    desc: "A serene mountain reservoir high on the Bucegi plateau, ringed by peaks and forest. A scenic drive up from Sinaia via the Ialomița valley, often paired with the nearby Ialomiței Cave." },
  { id: 50, name: "Ialomiței Cave (Peștera Ialomiței)", stop: "sinaia", cat: "nature", coords: [45.3930, 25.4369], duration: "1 h",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Manastirea_Pestera_Ialomitei.jpg/960px-Manastirea_Pestera_Ialomitei.jpg",
    note: "Cave beside a cliff-side monastery, deep in the Bucegi Mountains.",
    desc: "A striking limestone cave set into the cliff next to the Ialomiței hermitage on the Bucegi plateau. Guided walks lead through illuminated chambers; the dramatic gorge setting is worth the trip alone." },
  { id: 51, name: "Pârtia Kalinderu (Bușteni slides)", stop: "sinaia", cat: "viewpoint", coords: [45.4197, 25.5248], duration: "1–2 h",
    note: "Bușteni ski slope with gondola and summer mountain activities.",
    desc: "The Kalinderu slope above Bușteni, served by its own gondola — ski runs in winter and a base for cable-car rides and mountain walks in summer, beneath the cliffs of the Bucegi." },
  { id: 52, name: "Capra Waterfall (Cascada Capra)", stop: "curtea", cat: "nature",   coords: [45.5864, 24.6308], duration: "30–45 min",
    note: "Roadside waterfall on the Transfăgărășan, just below Bâlea.",
    desc: "A graceful cascade tumbling right beside the Transfăgărășan highway on the southern approach to Bâlea Lake — an easy, photogenic stop where the road begins its final climb to the tunnel." },
  { id: 53, name: "Belvedere Lacul Vidraru",        stop: "curtea", cat: "viewpoint", coords: [45.4353, 24.6215], duration: "20–30 min",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Lacul_Vidraru.jpg/960px-Lacul_Vidraru.jpg",
    note: "Panoramic viewpoint over Lake Vidraru and the surrounding peaks.",
    desc: "A scenic overlook above the fjord-like Vidraru reservoir on the Transfăgărășan, taking in the sweep of blue water hemmed by forested mountains — a perfect photo pause on the drive up the valley." },
  { id: 54, name: "Transfăgărășan Treehouse Village", stop: "curtea", cat: "viewpoint", coords: [45.4070, 24.6369], duration: "30 min–stay",
    note: "Cabins/treehouses set among the forest along the Transfăgărășan.",
    desc: "A cluster of A-frame cabins and treehouses tucked into the forest along the Transfăgărășan near Curtea de Argeș — a scenic spot to break the drive or stay overnight amid the peaks." },
  { id: 55, name: "Albota Trout Farm",              stop: "sibiu",  cat: "nature",    coords: [45.6979, 24.6110], duration: "1–2 h",
    note: "Trout farm with lakes and restaurant at the foot of the Transfăgărășan.",
    desc: "A tranquil trout farm and lakeside restaurant at the northern base of the Transfăgărășan near Cârțișoara — feed the fish, walk the ponds, and stop for fresh-grilled trout before or after the mountain drive." },
  { id: 56, name: "Therme Bucharest",               stop: "snagov", cat: "nature",    coords: [44.6051, 26.0854], duration: "half day",
    note: "Vast thermal-water spa & water park near Bucharest airport (Balotești).",
    desc: "One of Europe's largest wellness and thermal-water complexes, just north of Bucharest at Balotești — pools, slides, palm-filled botanical galleries and saunas. An easy relaxing stop close to the airport at the start or end of the trip." },
];

// Hotels with full contact details
export const HOTELS = {
  snagov: {
    name: "Hotel Snagov Club",
    address: "Strada Aleea Nufărului nr. 1B, Snagov Sat, Ilfov, 077165",
    phone: "+40 728 210 075",
    fax: "+40 21 352 61 53",
    email: "reservation@snagovclub.ro",
    website: "https://snagovclub.ro",
    mapsUrl: "https://maps.google.com/?q=Snagov+Club+Aleea+Nufarului+1B+Snagov+Romania",
    coords: [44.7095, 26.1530],
    about: "Award-winning boutique hotel on the shores of Lake Snagov. Private terrace, boat riding, kayak and bike rentals.",
    nights: 1, rooms: 4, price: "₪2,183", cancellation: "No refund", confirmed: true,
    dates: "Aug 6 → Aug 7",
  },
  sinaia: {
    name: "Hotel Sinaia",
    address: "Bd. Carol I, Nr. 8, Sinaia, Prahova 106100",
    phone: "+40 244 302 900",
    email: "rezervari@hotelsinaia.ro",
    website: "https://www.hotelsinaia.ro",
    mapsUrl: "https://maps.google.com/?q=Hotel+Sinaia+Bd+Carol+I+8+Sinaia+Romania",
    coords: [45.3535, 25.5520],
    about: "Mountain hotel centrally located on Sinaia's main boulevard.",
    nights: 2, rooms: 4, price: "₪5,881", cancellation: "Free cancellation", confirmed: true,
    dates: "Aug 7 → Aug 9",
  },
  brasov: {
    name: "The Pines Boutique Villa",
    address: "Str. Cloșca, nr. 44, Brașov, 500040",
    phone: "+40 738 124 966",
    email: "brasov@thepines.ro",
    website: "https://thepines.ro/the-pines-brasov-en",
    mapsUrl: "https://maps.google.com/?q=The+Pines+Boutique+Villa+Str+Closca+44+Brasov+Romania",
    coords: [45.6450, 25.5940],
    about: "Small luxury boutique villa, Scandinavian/Nordic style. Rated 9.6/10 on Booking.com (273 reviews). #1 boutique villa in Brașov.",
    nights: 2, rooms: 4, price: "₪5,790", cancellation: "Free cancellation", confirmed: true,
    dates: "Aug 9 → Aug 11",
  },
  sibiu: {
    name: "Pensiunea La Vâltoare",
    address: "Str. Mărăjdiei, Nr. 9, Gura Râului, Sibiu",
    phone: "+40 753 999 960",
    email: "rezervari@valtoare.ro",
    website: "https://valtoare.ro",
    mapsUrl: "https://maps.google.com/?q=Pensiunea+La+Valtoare+Str+Marajdiei+9+Gura+Raului+Sibiu+Romania",
    coords: [45.6700, 23.9150],
    about: "Rural guesthouse in Gura Râului village, 18 km from Sibiu city. Mountain setting at the foothills of Cindrel Mountains. Features sauna & restaurant. Rated 9.8/10 on Booking.com (136 reviews).",
    nights: 3, rooms: 4, price: "₪10,012", cancellation: "Free cancellation", confirmed: true,
    dates: "Aug 11 → Aug 14",
    note: "18 km from Sibiu city center",
  },
  curtea: {
    name: "Old Court",
    address: "Strada Lascăr Catargiu 19, 115300 Curtea de Argeș",
    phone: "+40 749 761 768",
    website: "https://www.booking.com/hotel/the-old-court-1830",
    mapsUrl: "https://maps.google.com/?q=Old+Court+Strada+Laskar+Catargiu+19+Curtea+de+Arges+Romania",
    coords: [45.1392, 24.6792],
    about: "Historic guesthouse in a beautiful old building with garden views, BBQ and charming courtyard. 30 km from Vidraru Dam. Rated 9.4/10 on Booking.com (996 reviews).",
    nights: 2, rooms: 5, price: "₪2,048", cancellation: "Free cancellation", confirmed: true,
    dates: "Aug 14 → Aug 16",
  },
};

export const trip = {
  slug: "romania",
  title: "Romania Road Trip",
  country: "Romania",
  flag: "🇷🇴",
  startDate: "2026-08-06",
  subtitle: "10 days through Transylvania",
  heroImage: "https://images.unsplash.com/photo-1601244005535-a48d21d951ac?w=1200&q=80",
  dates: "Aug 6 – 16, 2026",
  totalKm: 638,
  flight: {
    outbound: { number: "LY573",  airline: "EL AL", from: "TLV", to: "BUH", date: "Thu, Aug 6",  departs: "04:45", arrives: "07:25", bookingRef: "7IGKV6" },
    return:   { number: "LY9492", airline: "EL AL", from: "BUH", to: "TLV", date: "Sun, Aug 16", departs: "20:45", arrives: "23:20", bookingRef: "7ILXY6" },
  },
  car: {
    pickup: { location: "Bucharest Otopeni Airport (OTP)", time: "11:00 AM", date: "Thu, Aug 6" },
    return: { location: "Bucharest Otopeni Airport (OTP)", time: "4:30 PM",  date: "Sun, Aug 16" },
  },
  days: [
    {
      id: 1, date: "Thu, Aug 6", type: "travel",
      from: "Bucharest Airport (OTP)", to: "Snagov",
      arrival: { flight: "LY573", lands: "07:25", carPickup: "11:00 AM" },
      drive: { duration: "35 min", distance: "40 km", route: "A3 north" },
      hotelId: "snagov", stopId: "snagov",
      summary: "Land in Bucharest at 07:25, pick up the car at 11:00 and head to Snagov — only 40 km north. 1 night at Hotel Snagov Club on the shores of Lake Snagov. Afternoon walk around the lake and visit to the famous monastery — Vlad the Impaler's legendary tomb.",
    },
    {
      id: 2, date: "Fri, Aug 7", type: "travel",
      from: "Snagov", to: "Sinaia",
      drive: { duration: "1 h 30 min", distance: "120 km", route: "A3 → DN1" },
      hotelId: "sinaia", stopId: "sinaia",
      summary: "Morning drive 120 km south into the Carpathians. Arrive Sinaia and check in to Hotel Sinaia on the main boulevard. Afternoon visit to the stunning Peleș Castle — one of Romania's crown jewels and Tripadvisor #1 in Sinaia.",
    },
    {
      id: 3, date: "Sat, Aug 8", type: "stay", location: "Sinaia",
      hotelId: "sinaia", stopId: "sinaia",
      summary: "Full day in Sinaia. Pelișor Castle in the morning (Art Nouveau, built for Queen Marie), cable car up to Cota 2,000 for panoramic Carpathian views. Evening stroll through Sinaia Monastery complex.",
    },
    {
      id: 4, date: "Sun, Aug 9", type: "travel",
      from: "Sinaia", to: "Brașov",
      drive: { duration: "45 min", distance: "48 km", route: "DN1" },
      hotelId: "brasov", stopId: "brasov",
      summary: "Short 45-min drive to Brașov. Check in to The Pines Boutique Villa (rated #1 in Brașov). Explore the famous medieval Old Town — Council Square and the towering Black Church. Evening walk to Catherine's Gate.",
    },
    {
      id: 5, date: "Mon, Aug 10", type: "stay", location: "Brașov",
      hotelId: "brasov", stopId: "brasov",
      summary: "Day trip to Bran Castle ('Dracula's Castle') and nearby Râșnov Fortress — both within 30 min. Consider the Libearty Bear Sanctuary in Zărnești. Back in the evening to explore Rope Street, the narrowest street in Romania.",
    },
    {
      id: 6, date: "Tue, Aug 11", type: "travel",
      from: "Brașov", to: "Sibiu / Gura Râului",
      drive: { duration: "2 h 30 min", distance: "170 km", route: "DN1 via Transfăgărășan — scenic!" },
      hotelId: "sibiu", stopId: "sibiu",
      summary: "The most scenic drive of the trip — Transfăgărășan highway cuts through the highest peaks of the Carpathians. Arrive at Pensiunea La Vâltoare in Gura Râului village, 18 km from Sibiu. 3 nights here at this 9.8-rated guesthouse.",
    },
    {
      id: 7, date: "Wed, Aug 12", type: "stay", location: "Sibiu",
      hotelId: "sibiu", stopId: "sibiu",
      summary: "Full day in Sibiu — one of Europe's most beautiful medieval cities. Start at Piața Mare (Great Square), visit Brukenthal Museum, cross the famous Bridge of Lies, and climb the Council Tower for views over the terracotta rooftops.",
    },
    {
      id: 8, date: "Thu, Aug 13", type: "stay", location: "Sibiu",
      hotelId: "sibiu", stopId: "sibiu",
      summary: "Day trip to Sighișoara — Dracula's birthplace and UNESCO World Heritage site, only 1 hour away. Explore the fortified old town on the hill. Return to Sibiu for the vast ASTRA Open Air Museum in Dumbrava Forest.",
    },
    {
      id: 9, date: "Fri, Aug 14", type: "travel",
      from: "Sibiu / Gura Râului", to: "Curtea de Argeș",
      drive: { duration: "2 h", distance: "100 km", route: "DN7C → DN7 (via Transfăgărășan possible)" },
      hotelId: "curtea", stopId: "curtea",
      summary: "Drive through the Olt valley to Curtea de Argeș — the former medieval capital of Wallachia. Check in to Old Court (9.4 rated, 996 reviews). Afternoon visit to the magnificent Curtea de Argeș Cathedral, Romania's Royal Necropolis.",
    },
    {
      id: 10, date: "Sat, Aug 15", type: "stay", location: "Curtea de Argeș",
      hotelId: "curtea", stopId: "curtea",
      summary: "Drive to Poienari Citadel — the REAL Dracula fortress (1,480 steps up a cliff!). Then to Vidraru Dam with dramatic lake scenery. The full Transfăgărășan road is accessible from here. Last evening of the trip.",
    },
    {
      id: 11, date: "Sun, Aug 16", type: "travel",
      from: "Curtea de Argeș", to: "Bucharest Airport (OTP)",
      drive: { duration: "2 h", distance: "160 km", route: "DN7 → A1" },
      departure: { carReturn: "4:30 PM", flight: "LY9492", departs: "20:45" },
      hotelId: null, stopId: "otp",
      summary: "Head back to Bucharest. Return the car at OTP by 4:30 PM. 4+ hours buffer before LY9492 departs at 20:45. Lands Tel Aviv 23:20. End of trip.",
    },
  ],
};

export function getDayRangeByStop() {
  const map = {}
  trip.days.forEach(d => {
    if (!d.stopId || d.stopId === 'otp') return
    if (!map[d.stopId]) map[d.stopId] = []
    map[d.stopId].push(d.id)
  })
  const result = {}
  Object.entries(map).forEach(([stopId, ids]) => {
    const min = Math.min(...ids), max = Math.max(...ids)
    result[stopId] = min === max ? `Day ${min}` : `Day ${min}–${max}`
  })
  return result
}
